debug_level: 0

base_frame_id: "base"
odom_frame_id: "odom_vilens"
payload_cloud_topic: "/local_mapping/payload_in_local"
payload_path_topic: "/local_mapping/path"
tree_meshes_topic: "/digiforest_forest_analysis/tree_meshes"

tree_manager:
  distance_threshold: 1.0
  reco_min_angle_coverage: 180
  reco_min_distance: 4.0

cloth:
  enabled: False
  cell_size: 2

clustering:
  method: "voronoi"
  hough_filter_radius: 0.1 
  crop_lower_bound: 1.0
  crop_upper_bound: 3.0
  max_cluster_radius: 3.0
  n_threads: 1
  cluster_2d: False
  distance_calc_point_fraction: 0.1

fitting:
  slice_heights: 0.5
  slice_thickness: 0.3
  outlier_radius: 0.02
  max_center_deviation: 0.05
  max_radius_deviation: 0.05
  filter_min_points: 10
  min_hough_vote: 0.1
  grid_res: 0.01
  point_ratio: 0.2
  entropy_weighting: 10.0
  max_consecutive_fails: 3
  max_height: 15.0
  save_debug_results: False
  n_threads: 1  