debug_level: 1

base_frame_id: "base"
payload_cloud_topic: "/local_mapping/payload_in_local"
tree_meshes_topic: "/local_mapping/tree_meshes"

ground_segmentation_enabled: False
ground_segmentation_method: "csf"
ground_segmentation_cell_size: 2

clustering_method: "voronoi"
clustering_hough_filter_radius: 0.1
clustering_crop_lower_bound: 1.0
clustering_crop_upper_bound: 3.0
clustering_max_cluster_radius: 3.0
clustering_n_threads: 8
clustering_cluster_2d: False

fitting_height_increment: 0.5
