debug_level: 0

id:
  base_frame: "base_vilens_optimized"
  odom_frame: "odom_vilens"
  map_frame: "map"

topic:
  payload_cloud: "/local_mapping/payload_in_local"
  payload_path: "/local_mapping/path"
  posegraph_update: "/vilens_slam/pose_graph"
  stem_meshes: "/digiforest_forest_analysis/stem_meshes"
  canopy_meshes: "/digiforest_forest_analysis/canopy_meshes"
  terrain_model: "/digiforest_forest_analysis/terrain_model"

tree_manager:
  distance_threshold: 0.5
  reco_min_angle_coverage: 180
  reco_min_distance: 4.0

terrain:
  enabled: True
  smoothing: False
  cell_size: 1
  confidence_stds: [3, 10, 10]
  confidence_sensor_weight: 0.9999
  use_embree: True

clustering:
  crop_radius: 20.0
  hough_filter_radius: 0.1 
  crop_lower_bound: 3.0
  crop_upper_bound: 5.0
  max_cluster_radius: 2.0
  n_threads: 8
  distance_calc_point_fraction: 0.1

fitting:
  slice_heights: 0.5
  slice_thickness: 0.3
  outlier_radius: 0.02
  max_center_deviation: 0.05
  max_radius_deviation: 0.05
  filter_min_points: 10
  min_hough_vote: 0.1
  grid_res: 0.01
  point_ratio: 0.2
  entropy_weighting: 10.0
  max_consecutive_fails: 3
  max_height: 15.0
  save_debug_results: False
  n_threads: 1  
  generate_canopy: True